# Generated by Django 2.2.6 on 2019-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
